# Site settings
name: blog
email: 805429509@qq.com
baseurl: "/blog"
description: Actually, less is more!
meta_description: 个人博客
motto: It's our wits that make us men.


#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']


highlighter: Pygments

# Build settings
markdown: kramdown
